export const RECEIVE_COINS_LIST = 'RECEIVE_COINS_LIST';
export const UPDATE_TOP_COIN_PRICES = 'UPDATE_TOP_COIN_PRICES';
export const SET_UPDATE_TIME = 'SET_UPDATE_TIME';
export const RECEIVE_PREFERRED_CURRENCY = 'RECEIVE_PREFERRED_CURRENCY';
export const INIT_ADDON = 'INIT_ADDON';
export const UPDATE_ADDON_DATA = 'UPDATE_ADDON_DATA';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
