export const RECEIVE_TOP_COIN_LIST = 'RECEIVE_TOP_COIN_LIST';
export const RECEIVE_PREFERRED_CURRENCY = 'RECEIVE_PREFERRED_CURRENCY';
export const INIT_ADDON = 'INIT_ADDON';
export const UPDATE_ADDON_DATA = 'UPDATE_ADDON_DATA';
